# Generated by Django 4.1 on 2022-09-02 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_link', models.CharField(max_length=250, unique=True)),
                ('company_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('company_link', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('ratings', models.CharField(max_length=100)),
                ('reviews', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('posted', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
